DELIMITER //

CREATE PROCEDURE CFB_CREATE_USER (
    IN IN_USERNAME VARCHAR(32),
    IN IN_PW VARCHAR(32)
)

BEGIN

    INSERT INTO CFB_USERS (USER_ID, USERNAME, PW)
        VALUES (NULL, IN_USERNAME, IN_PW);
    
    COMMIT;
    
    INSERT INTO CFB_USER_PICKS (USER_ID, GAME_ID, SELECTED_SCHOOL)
        SELECT 
            (SELECT MAX(U.USER_ID) FROM CFB_USERS U), 
            G.GAME_ID, 
            NULL
        FROM 
            CFB_GAMES G;

    COMMIT;

END //

DELIMITER ;