CREATE PROCEDURE CREATE_CFB_PICKEM_CONSTRAINTS()

BEGIN

    -- Primary Keys
    ALTER TABLE CFB_GAMES
    ADD CONSTRAINT PK_GAMES PRIMARY KEY (GAME_ID);

    ALTER TABLE CFB_SCHOOLS
    ADD CONSTRAINT PK_SCHOOLS PRIMARY KEY (SCHOOL_ID);

    ALTER TABLE CFB_CONFERENCES
    ADD CONSTRAINT PK_CONFERENCES PRIMARY KEY (DIVISION_ID);

    ALTER TABLE CFB_LOCATIONS
    ADD CONSTRAINT PK_LOCATIONS PRIMARY KEY (LOCATION_ID);

    ALTER TABLE CFB_USER_PICKS
    ADD CONSTRAINT PK_PICKS PRIMARY KEY (USER_ID, GAME_ID);


    -- Foreign Keys
    ALTER TABLE CFB_GAMES
    ADD CONSTRAINT FK_GAME_AWAY_SCHOOL
    FOREIGN KEY (AWAY_SCHOOL) REFERENCES CFB_SCHOOLS(SCHOOL_ID);

    ALTER TABLE CFB_GAMES
    ADD CONSTRAINT FK_GAME_HOME_SCHOOL
    FOREIGN KEY (HOME_SCHOOL) REFERENCES CFB_SCHOOLS(SCHOOL_ID);

    ALTER TABLE CFB_GAMES
    ADD CONSTRAINT FK_GAME_LOCATION
    FOREIGN KEY (GAME_LOCATION) REFERENCES CFB_LOCATIONS(LOCATION_ID);

    ALTER TABLE CFB_SCHOOLS
    ADD CONSTRAINT FK_SCHOOL_DIVISION
    FOREIGN KEY (DIVISION) REFERENCES CFB_CONFERENCES(DIVISION_ID);

    ALTER TABLE CFB_USER_PICKS
    ADD CONSTRAINT FK_PICK_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES CFB_USERS(USER_ID);

    ALTER TABLE CFB_USER_PICKS
    ADD CONSTRAINT FK_PICK_GAME_ID
    FOREIGN KEY (GAME_ID) REFERENCES CFB_GAMES(GAME_ID);

END;