DELIMITER //

CREATE PROCEDURE CREATE_NEW_USER (
    IN IN_USERNAME VARCHAR(32),
    IN IN_PW VARCHAR(32)
)

BEGIN

    INSERT INTO CFB_USERS (USER_ID, USERNAME, PW)
        VALUES (NULL, IN_USERNAME, IN_PW);
    
    INSERT INTO CFB_USER_PICKS (USER_ID, GAME_ID, SELECTED_SCHOOL)
        SELECT MAX(U.USER_ID), G.GAME_ID, NULL
        FROM CFB_USERS U, CFB_GAMES G;

END //

DELIMITER ;