CREATE PROCEDURE DELETE_CFB_PICKEM_DATA()

BEGIN

    DELETE FROM CFB_USER_PICKS;

    DELETE FROM CFB_USERS;

    DELETE FROM CFB_LOCATIONS;

    DELETE FROM CFB_CONFERENCES;

    DELETE FROM CFB_SCHOOLS;
 
    DELETE FROM CFB_GAMES;

END;