CREATE PROCEDURE DROP_CFB_PICKEM_CONSTRAINTS()

BEGIN

    -- Foreign Keys
    ALTER TABLE CFB_USER_PICKS
    DROP FOREIGN KEY FK_PICK_USER_ID;

    ALTER TABLE CFB_USER_PICKS
    DROP FOREIGN KEY FK_PICK_GAME_ID;

    ALTER TABLE CFB_SCHOOLS
    DROP FOREIGN KEY FK_SCHOOL_DIVISION;

    ALTER TABLE CFB_GAMES
    DROP FOREIGN KEY FK_GAME_LOCATION;

    ALTER TABLE CFB_GAMES
    DROP FOREIGN KEY FK_GAME_HOME_SCHOOL;

    ALTER TABLE CFB_GAMES
    DROP FOREIGN KEY FK_GAME_AWAY_SCHOOL;


    -- Primary Keys
    ALTER TABLE CFB_USER_PICKS
    DROP PRIMARY KEY;

    ALTER TABLE CFB_USERS
    DROP PRIMARY KEY;

    ALTER TABLE CFB_LOCATIONS
    DROP PRIMARY KEY;

    ALTER TABLE CFB_CONFERENCES
    DROP PRIMARY KEY;

    ALTER TABLE CFB_SCHOOLS
    DROP PRIMARY KEY;

    ALTER TABLE CFB_GAMES
    DROP PRIMARY KEY;

END;