CREATE PROCEDURE DROP_CFB_PICKEM_CONSTRAINTS()

BEGIN

    -- Foreign Keys
    ALTER TABLE CFB_USER_PICKS
    DROP CONSTRAINT FK_PICK_GAME_ID;

    ALTER TABLE CFB_USER_PICKS
    DROP CONSTRAINT FK_PICK_USER_ID;

    ALTER TABLE CFB_SCHOOLS
    DROP CONSTRAINT FK_SCHOOL_DIVISION;

    ALTER TABLE CFB_GAMES
    DROP CONSTRAINT FK_GAME_LOCATION;

    ALTER TABLE CFB_GAMES
    DROP CONSTRAINT FK_GAME_HOME_SCHOOL;

    ALTER TABLE CFB_GAMES
    DROP CONSTRAINT FK_GAME_AWAY_SCHOOL;


    -- Primary Keys
    ALTER TABLE CFB_USER_PICKS
    DROP CONSTRAINT PK_PICKS;

    ALTER TABLE CFB_USERS
    DROP CONSTRAINT PK_USER;

    ALTER TABLE CFB_LOCATIONS
    DROP CONSTRAINT PK_LOCATIONS;

    ALTER TABLE CFB_CONFERENCES
    DROP CONSTRAINT PK_CONFERENCES;

    ALTER TABLE CFB_SCHOOLS
    DROP CONSTRAINT PK_SCHOOLS;

    ALTER TABLE CFB_GAMES
    DROP CONSTRAINT PK_GAMES;

END