DELIMITER //

CREATE PROCEDURE SUBMIT_PICK (
    IN IN_USERID INT,
    IN IN_GAMEID INT,
    IN IN_SELECTED_SCHOOL SMALLINT
)

BEGIN

    UPDATE CFB_USER_PICKS
    SET SELECTED_SCHOOL = IN_SELECTED_SCHOOL
    WHERE USER_ID = IN_USERID
        AND GAME_ID = IN_GAMEID;

END //

DELIMITER ;